# This is a basic workflow to help you get started with Actions

name: Patreon RSS Feed updater

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-feed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4

      # Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib beautifulsoup4

      - name: Run python script
        env:
          GMAIL_TOKEN: ${{secrets.GMAIL_TOKEN}}
        run: python update_feed.py

      - name: Commit feed.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "Updated the RSS feed with new posts"
          git push
